### ISSUE TITLE
No longer working on the latest mpv build

### ISSUE THREAD

**Issue by Zabooby** [hdbhdb/mpv-live-filters#1]
The last time this script was updated was 2 years ago and it no longer works on windows in the latest build. Any plans to update it?

**Comment by hdb** [comment]
what is your mpv version and could you include either the error message you are seeing or a log file?

**Comment by Zabooby** [comment]
I'm on mpv 0.34.0-285-g9ffaa6b81b. I don't get any error messages the vf just doesn't work. I use a gui not a cmd for mpv how would I check logs?

**Comment by Zabooby** [comment]
Nvm here is the error I get when I try > tblend=c0_mode=difference,eq=contrast=2    
https://imgur.com/gallery/7P6bOwA

**Comment by hdb** [comment]
thanks - I am unable to reproduce this error on the latest Windows git build so I think this is a downstream change in the GUI you are using. Looks like it should still work though if you pass the `tblend` and `eq` commands one at a time rather than in the same line
